// @generated by protoc-gen-es v0.2.1 with parameter "target=ts"
// @generated from file tendermint/store/types.proto (package tendermint.store, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import type {BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage} from "@bufbuild/protobuf";
import {Message, proto3, protoInt64} from "@bufbuild/protobuf";

/**
 * @generated from message tendermint.store.BlockStoreState
 */
export class BlockStoreState extends Message<BlockStoreState> {
  /**
   * @generated from field: int64 base = 1;
   */
  base = protoInt64.zero;

  /**
   * @generated from field: int64 height = 2;
   */
  height = protoInt64.zero;

  constructor(data?: PartialMessage<BlockStoreState>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "tendermint.store.BlockStoreState";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "base", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
    { no: 2, name: "height", kind: "scalar", T: 3 /* ScalarType.INT64 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BlockStoreState {
    return new BlockStoreState().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BlockStoreState {
    return new BlockStoreState().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BlockStoreState {
    return new BlockStoreState().fromJsonString(jsonString, options);
  }

  static equals(a: BlockStoreState | PlainMessage<BlockStoreState> | undefined, b: BlockStoreState | PlainMessage<BlockStoreState> | undefined): boolean {
    return proto3.util.equals(BlockStoreState, a, b);
  }
}

