// @generated by protoc-gen-es v0.2.0 with parameter "target=ts"
// @generated from file state.proto (syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import type {BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage} from "@bufbuild/protobuf";
import {Message, proto3, protoInt64, Struct} from "@bufbuild/protobuf";

/**
 * @generated from message BEP21MilestoneParameters
 */
export class BEP21MilestoneParameters extends Message<BEP21MilestoneParameters> {
  /**
   * @generated from field: google.protobuf.Struct application = 1;
   */
  application?: Struct;

  /**
   * @generated from field: google.protobuf.Struct consensus = 2;
   */
  consensus?: Struct;

  /**
   * @generated from field: google.protobuf.Struct denominations = 3;
   */
  denominations?: Struct;

  /**
   * @generated from field: google.protobuf.Struct mandatory_modules = 4;
   */
  mandatoryModules?: Struct;

  /**
   * @generated from field: google.protobuf.Struct transactions = 5;
   */
  transactions?: Struct;

  constructor(data?: PartialMessage<BEP21MilestoneParameters>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "BEP21MilestoneParameters";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "application", kind: "message", T: Struct },
    { no: 2, name: "consensus", kind: "message", T: Struct },
    { no: 3, name: "denominations", kind: "message", T: Struct },
    { no: 4, name: "mandatory_modules", kind: "message", T: Struct },
    { no: 5, name: "transactions", kind: "message", T: Struct },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BEP21MilestoneParameters {
    return new BEP21MilestoneParameters().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BEP21MilestoneParameters {
    return new BEP21MilestoneParameters().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BEP21MilestoneParameters {
    return new BEP21MilestoneParameters().fromJsonString(jsonString, options);
  }

  static equals(a: BEP21MilestoneParameters | PlainMessage<BEP21MilestoneParameters> | undefined, b: BEP21MilestoneParameters | PlainMessage<BEP21MilestoneParameters> | undefined): boolean {
    return proto3.util.equals(BEP21MilestoneParameters, a, b);
  }
}

/**
 * @generated from message BEP21Milestone
 */
export class BEP21Milestone extends Message<BEP21Milestone> {
  /**
   * @generated from field: uint64 block_number = 1;
   */
  blockNumber = protoInt64.zero;

  /**
   * @generated from field: BEP21MilestoneParameters parameters = 2;
   */
  parameters?: BEP21MilestoneParameters;

  constructor(data?: PartialMessage<BEP21Milestone>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime = proto3;
  static readonly typeName = "BEP21Milestone";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "block_number", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "parameters", kind: "message", T: BEP21MilestoneParameters },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BEP21Milestone {
    return new BEP21Milestone().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BEP21Milestone {
    return new BEP21Milestone().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BEP21Milestone {
    return new BEP21Milestone().fromJsonString(jsonString, options);
  }

  static equals(a: BEP21Milestone | PlainMessage<BEP21Milestone> | undefined, b: BEP21Milestone | PlainMessage<BEP21Milestone> | undefined): boolean {
    return proto3.util.equals(BEP21Milestone, a, b);
  }
}

