// @generated by protoc-gen-connect-web v0.3.0 with parameter "target=ts"
// @generated from file tendermint/rpc/grpc/types.proto (package tendermint.rpc.grpc, syntax proto3)
/* eslint-disable */
/* @ts-nocheck */

import {RequestBroadcastTx, RequestPing, ResponseBroadcastTx, ResponsePing} from "./types_pb.js";
import {MethodKind} from "@bufbuild/protobuf";

/**
 * @generated from service tendermint.rpc.grpc.BroadcastAPI
 */
export const BroadcastAPI = {
  typeName: "tendermint.rpc.grpc.BroadcastAPI",
  methods: {
    /**
     * @generated from rpc tendermint.rpc.grpc.BroadcastAPI.Ping
     */
    ping: {
      name: "Ping",
      I: RequestPing,
      O: ResponsePing,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc tendermint.rpc.grpc.BroadcastAPI.BroadcastTx
     */
    broadcastTx: {
      name: "BroadcastTx",
      I: RequestBroadcastTx,
      O: ResponseBroadcastTx,
      kind: MethodKind.Unary,
    },
  }
} as const;

